# ----------- Création du pod en fonction du code d'origin et des besoins de variables d'environnement ... --------------

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lnd
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sengsathit/brief-api:latest
        ports:
        - containerPort: 8000
        # ---------------Accès Mysql -------------------
        # --------------bil faut ajouter toutes les variables d'environnement que demande l'API dans l'image docker ---------------
        env:
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database-name
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database-url
        - name: ROOT_PATH
          value: "/lnd"
        # ----------------- Probes -----------------

        # ----------------- Vérifie que le pod est vivant -----------------
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        
        # ----------------- Vérifie que le pod est prêt à recevoir-----------
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---

# --------------- Service associé au pod --------------

apiVersion: v1
kind: Service
metadata:
  namespace: lnd
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8000